// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ldqabfqwmdapqzhrjgtt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkcWFiZnF3bWRhcHF6aHJqZ3R0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2ODgwMzUsImV4cCI6MjA3MTI2NDAzNX0.etvRgq2u3c7yRNAcbvmGrRmSaIB0uh0u81Hmmk_tE4g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});